// --------------------- Requisições Categoria --------------------- 

GET http://localhost:3000/category HTTP/1.1
content-type: application/json

####

GET http://localhost:3000/category/10 HTTP/1.1
content-type: application/json

####

POST http://localhost:3000/category HTTP/1.1
content-type: application/json

{  
  "description": "categoria 11"  
}

####

PUT http://localhost:3000/category/1 HTTP/1.1
content-type: application/json

{  
  "description": "Categoria TESTE 1"  
}

####

DELETE  http://localhost:3000/category/8 HTTP/1.1
content-type: application/json

