// --------------------- Requisições Categoria --------------------- 

GET http://localhost:3000/category HTTP/1.1
content-type: application/json

####

POST http://localhost:3000/category HTTP/1.1
content-type: application/json

{  
  "description": "categoria 1"  
}

####

PUT http://localhost:3000/category/1 HTTP/1.1
content-type: application/json

{  
  "description": "Categoria TESTE 1"  
}

####

DELETE  http://localhost:3000/category/3 HTTP/1.1
content-type: application/json

###
//--------------------- Requisições Usuario ---------------------------

GET http://localhost:3000/user HTTP/1.1
content-type: application/json

####

POST http://localhost:3000/user HTTP/1.1
content-type: application/json

{  
  "first_name": "José",
  "last_name": "Teste",
  "password": "123456"
}

####

PUT http://localhost:3000/user/1 HTTP/1.1
content-type: application/json

{    
  "password": 54321
}

####

DELETE  http://localhost:3000/user/3 HTTP/1.1
content-type: application/json



//----------------------
